#!/bin/bash
# Script called by autostart.
# by ben0bi@web4me in 2016

# Server takes 2 parameters: Width and Height.
# Start the server with 100 (10x10) LEDs.

sudo -S node node_module/node_LED_server.js 10 10 <autoboot/sudo_passwd

