#!/bin/bash
# Script called by autostart.
# by ben0bi@web4me in 2016

# Server takes 2 parameters: Width and Height.
# Start the server with 100 (10x10) LEDs.

# Command> node_LED_server.js preLEDS width height afterLEDS

echo "Starting server."
sudo -S /home/pi/nodejs/bin/node node_LED_server.js 0 10 2 0 <autoboot/sudo_passwd
echo "done."

