#!/bin/bash
# Script called by autostart.
# by ben0bi@web4me in 2016

# Server takes 4 parameters: preLEDs Width Height afterLEDs.
# Start the server with 100 (10x10) LEDs.

# Command> node_LED_server.js preLEDS width height afterLEDS

echo "Starting server. (Manual Node)"
/home/pi/nodejs/bin/node --version
sudo -S /home/pi/nodejs/bin/node /home/pi/Documents/ThereWillBeLED/node_LED_server.js 0 10 5 0 </home/pi/Documents/ThereWillBeLED/autoboot/sudo_passwd
echo "done."

